STATS = { 'bundleURLTemplate': 'cv-corpus-9.0-2022-04-27/cv-corpus-9.0-2022-04-27-{locale}.tar.gz',
  'date': '2022-04-27',
  'locales': { 
               'en': { 'avgDurationSecs': 5.146,
                       'buckets': { 'dev': 16335,
                                    'invalidated': 242945,
                                    'other': 267228,
                                    'reported': 3903,
                                    'test': 16335,
                                    'train': 890116,
                                    'validated': 1556254},
                       'checksum': '7c789a325e1d9f16137c1aeab9f45a1fde049a39b8fbf49e9ef4a8827ae67eae',
                       'clips': 2066427,
                       'duration': 10632910099,
                       'reportedSentences': 3842,
                       'size': 76768058135,
                       'splits': { 'accent': {'': 1},
                                   'age': { '': 0.37,
                                            'eighties': 0,
                                            'fifties': 0.05,
                                            'fourties': 0.1,
                                            'nineties': 0,
                                            'seventies': 0.01,
                                            'sixties': 0.04,
                                            'teens': 0.06,
                                            'thirties': 0.13,
                                            'twenties': 0.24},
                                   'gender': { '': 0.37,
                                               'female': 0.15,
                                               'male': 0.46,
                                               'other': 0.02}},
                       'totalHrs': 2953.58,
                       'users': 81085,
                       'validDurationSecs': 8007787.777,
                       'validHrs': 2224.38},
               'ja': { 'avgDurationSecs': 4.781,
                       'buckets': { 'dev': 4445,
                                    'invalidated': 2195,
                                    'other': 310,
                                    'reported': 129,
                                    'test': 4495,
                                    'train': 6212,
                                    'validated': 34715},
                       'checksum': '6d142a6969698a8505fa32e5fd4636e502116ded6d0e6b49e66340480cb70150',
                       'clips': 37220,
                       'duration': 177935145,
                       'reportedSentences': 129,
                       'size': 1081598283,
                       'splits': { 'accent': {'': 1},
                                   'age': { '': 0.24,
                                            'fifties': 0.01,
                                            'fourties': 0.28,
                                            'seventies': 0,
                                            'sixties': 0,
                                            'teens': 0.04,
                                            'thirties': 0.1,
                                            'twenties': 0.32},
                                   'gender': { '': 0.21,
                                               'female': 0.26,
                                               'male': 0.52,
                                               'other': 0}},
                       'totalHrs': 49.42,
                       'users': 619,
                       'validDurationSecs': 165959.66,
                       'validHrs': 46.09},
               'zh-CN': { 'avgDurationSecs': 5.181,
                          'buckets': { 'dev': 9740,
                                       'invalidated': 6689,
                                       'other': 14066,
                                       'reported': 458,
                                       'test': 9747,
                                       'train': 23539,
                                       'validated': 48516},
                          'checksum': '36faeffbdbbdeab6a8994ceddc3df326503777754141f9135c24fd87d1a301a0',
                          'clips': 69271,
                          'duration': 358872900,
                          'reportedSentences': 445,
                          'size': 2637465454,
                          'splits': { 'accent': {'': 1},
                                      'age': { '': 0.39,
                                               'fifties': 0,
                                               'fourties': 0.03,
                                               'nineties': 0,
                                               'sixties': 0,
                                               'teens': 0.09,
                                               'thirties': 0.11,
                                               'twenties': 0.38},
                                      'gender': { '': 0.39,
                                                  'female': 0.1,
                                                  'male': 0.51,
                                                  'other': 0.01}},
                          'totalHrs': 99.68,
                          'users': 4233,
                          'validDurationSecs': 251347.283,
                          'validHrs': 69.81},
               'zh-HK': { 'avgDurationSecs': 4.224,
                          'buckets': { 'dev': 5578,
                                       'invalidated': 4045,
                                       'other': 15366,
                                       'reported': 626,
                                       'test': 5578,
                                       'train': 8392,
                                       'validated': 87390},
                          'checksum': '02132780a56946a6069129e8c15541616de2ebe789e58599215028dc604bb618',
                          'clips': 106801,
                          'duration': 451153356,
                          'reportedSentences': 615,
                          'size': 3287174684,
                          'splits': { 'accent': {'': 1},
                                      'age': { '': 0.41,
                                               'fifties': 0.03,
                                               'fourties': 0.13,
                                               'seventies': 0,
                                               'sixties': 0,
                                               'teens': 0.02,
                                               'thirties': 0.11,
                                               'twenties': 0.31},
                                      'gender': { '': 0.37,
                                                  'female': 0.22,
                                                  'male': 0.41,
                                                  'other': 0.01}},
                          'totalHrs': 125.32,
                          'users': 2869,
                          'validDurationSecs': 369156.579,
                          'validHrs': 102.54},
               'zh-TW': { 'avgDurationSecs': 3.249,
                          'buckets': { 'dev': 4618,
                                       'invalidated': 4482,
                                       'other': 37593,
                                       'reported': 138,
                                       'test': 4618,
                                       'train': 6393,
                                       'validated': 74894},
                          'checksum': 'b40023ca8f5113a3766ba2d0844c3e846ff48eb1d4408d9ae912d4f9caa183eb',
                          'clips': 116969,
                          'duration': 380039242,
                          'reportedSentences': 139,
                          'size': 2719746719,
                          'splits': { 'accent': {'': 1},
                                      'age': { '': 0.28,
                                               'fifties': 0.04,
                                               'fourties': 0.1,
                                               'seventies': 0,
                                               'sixties': 0,
                                               'teens': 0.05,
                                               'thirties': 0.2,
                                               'twenties': 0.33},
                                      'gender': { '': 0.27,
                                                  'female': 0.25,
                                                  'male': 0.46,
                                                  'other': 0.02}},
                          'totalHrs': 105.56,
                          'users': 2002,
                          'validDurationSecs': 243335.063,
                          'validHrs': 67.59}},
  'multilingual': True,
  'name': 'Common Voice Corpus 9.0',
  'totalDuration': 72782088097,
  'totalHrs': 20217,
  'totalValidDurationSecs': 53904443,
  'totalValidHrs': 14973,
  'version': '9.0.0'}