STATS = { 'bundleURLTemplate': 'cv-corpus-5.1-2020-06-22/{locale}.tar.gz',
  'date': '2020-06-22',
  'locales': { 
               'en': { 'avgDurationSecs': 4.875,
                       'buckets': { 'dev': 16029,
                                    'invalidated': 166816,
                                    'other': 175084,
                                    'reported': 1354,
                                    'test': 16029,
                                    'train': 435947,
                                    'validated': 1085494},
                       'checksum': 'cb5903dc0775f96de81cd2fbaae4198be90a566cf3e9a0b2501111893d1dc98e',
                       'clips': 1427394,
                       'duration': 6957981334,
                       'reportedSentences': 1318,
                       'size': 53753543765,
                       'splits': { 'accent': { '': 0.51,
                                               'african': 0.01,
                                               'australia': 0.04,
                                               'bermuda': 0,
                                               'canada': 0.03,
                                               'england': 0.08,
                                               'hongkong': 0,
                                               'indian': 0.05,
                                               'ireland': 0.01,
                                               'malaysia': 0,
                                               'newzealand': 0.01,
                                               'other': 0.01,
                                               'philippines': 0,
                                               'scotland': 0.02,
                                               'singapore': 0,
                                               'southatlandtic': 0,
                                               'us': 0.23,
                                               'wales': 0},
                                   'age': { '': 0.37,
                                            'eighties': 0,
                                            'fifties': 0.04,
                                            'fourties': 0.1,
                                            'nineties': 0,
                                            'seventies': 0.01,
                                            'sixties': 0.04,
                                            'teens': 0.06,
                                            'thirties': 0.14,
                                            'twenties': 0.23},
                                   'gender': { '': 0.37,
                                               'female': 0.14,
                                               'male': 0.47,
                                               'other': 0.02}},
                       'totalHrs': 1932.77,
                       'users': 61528,
                       'validDurationSecs': 5291354.027,
                       'validHrs': 1469.82},
               'ja': { 'avgDurationSecs': 4.313,
                       'buckets': { 'dev': 1219,
                                    'invalidated': 1394,
                                    'other': 725,
                                    'reported': 88,
                                    'test': 1334,
                                    'train': 1642,
                                    'validated': 6158},
                       'checksum': 'aea95bc7d74c30e694b20815753920af4939539b79a1bd219f439b7da0a1f617',
                       'clips': 8277,
                       'duration': 35700744,
                       'reportedSentences': 89,
                       'size': 277993266,
                       'splits': { 'accent': {'': 1},
                                   'age': { '': 0.21,
                                            'fifties': 0.03,
                                            'fourties': 0.06,
                                            'sixties': 0,
                                            'teens': 0.04,
                                            'thirties': 0.05,
                                            'twenties': 0.6},
                                   'gender': { '': 0.14,
                                               'female': 0.1,
                                               'male': 0.76,
                                               'other': 0}},
                       'totalHrs': 9.91,
                       'users': 194,
                       'validDurationSecs': 26560.974,
                       'validHrs': 7.37},
               'zh-CN': { 'avgDurationSecs': 5.608,
                          'buckets': { 'dev': 8249,
                                       'invalidated': 4930,
                                       'other': 7368,
                                       'reported': 245,
                                       'test': 8273,
                                       'train': 16499,
                                       'validated': 33099},
                          'checksum': 'a78852ea07c7b101db2589b0ac541b2530536d5f9ca57d6d7839eb038a9a23b9',
                          'clips': 45397,
                          'duration': 254593542,
                          'reportedSentences': 245,
                          'size': 1982005342,
                          'splits': { 'accent': { '': 0.46,
                                                  '110000': 0.05,
                                                  '120000': 0,
                                                  '130000': 0.02,
                                                  '140000': 0.01,
                                                  '150000': 0,
                                                  '210000': 0.01,
                                                  '220000': 0,
                                                  '230000': 0.04,
                                                  '310000': 0.05,
                                                  '320000': 0.04,
                                                  '330000': 0.04,
                                                  '340000': 0.01,
                                                  '350000': 0.01,
                                                  '360000': 0.02,
                                                  '370000': 0.04,
                                                  '410000': 0.03,
                                                  '420000': 0.02,
                                                  '430000': 0.01,
                                                  '440000': 0.03,
                                                  '450000': 0.01,
                                                  '460000': 0.01,
                                                  '500000': 0.02,
                                                  '510000': 0.04,
                                                  '520000': 0,
                                                  '530000': 0,
                                                  '610000': 0.01,
                                                  '620000': 0,
                                                  '640000': 0,
                                                  '650000': 0,
                                                  '710000': 0.01,
                                                  '810000': 0},
                                      'age': { '': 0.39,
                                               'fifties': 0,
                                               'fourties': 0.03,
                                               'nineties': 0,
                                               'sixties': 0,
                                               'teens': 0.08,
                                               'thirties': 0.13,
                                               'twenties': 0.36},
                                      'gender': { '': 0.39,
                                                  'female': 0.1,
                                                  'male': 0.51,
                                                  'other': 0}},
                          'totalHrs': 70.72,
                          'users': 3333,
                          'validDurationSecs': 185624.417,
                          'validHrs': 51.56},
               'zh-HK': { 'avgDurationSecs': 4.822,
                          'buckets': { 'dev': 2805,
                                       'invalidated': 2535,
                                       'other': 14805,
                                       'reported': 197,
                                       'test': 2805,
                                       'train': 3379,
                                       'validated': 27643},
                          'checksum': '14359d47b37b8ae18e07492bdd0a723067f0d15379e1631ad3d4e9900abc112c',
                          'clips': 44983,
                          'duration': 216898152,
                          'reportedSentences': 189,
                          'size': 1662923573,
                          'splits': { 'accent': {'': 1},
                                      'age': { '': 0.39,
                                               'fifties': 0.04,
                                               'fourties': 0.14,
                                               'seventies': 0.01,
                                               'sixties': 0,
                                               'teens': 0.02,
                                               'thirties': 0.1,
                                               'twenties': 0.31},
                                      'gender': { '': 0.39,
                                                  'female': 0.24,
                                                  'male': 0.35,
                                                  'other': 0.02}},
                          'totalHrs': 60.24,
                          'users': 1576,
                          'validDurationSecs': 133288.478,
                          'validHrs': 37.02},
               'zh-TW': { 'avgDurationSecs': 3.213,
                          'buckets': { 'dev': 2627,
                                       'invalidated': 3430,
                                       'other': 19383,
                                       'reported': 34,
                                       'test': 2627,
                                       'train': 3120,
                                       'validated': 59942},
                          'checksum': '8199549605e9d5d211cb0c1e69c15d948d40985c5116dfe02456c92fe1ce309b',
                          'clips': 82755,
                          'duration': 265863297,
                          'reportedSentences': 35,
                          'size': 2055790976,
                          'splits': { 'accent': { '': 0.52,
                                                  'changhua_county': 0.01,
                                                  'chiayi_city': 0,
                                                  'chiayi_county': 0,
                                                  'hong_kong': 0,
                                                  'hsinchu_city': 0.01,
                                                  'hsinchu_county': 0,
                                                  'hualien_county': 0.01,
                                                  'kaohsiung_city': 0.03,
                                                  'keelung_city': 0,
                                                  'kinmen_county': 0,
                                                  'nantou_county': 0,
                                                  'new_taipei_city': 0.05,
                                                  'other': 0.09,
                                                  'pingtung_county': 0.01,
                                                  'taichung_city': 0.03,
                                                  'tainan_city': 0.04,
                                                  'taipei_city': 0.16,
                                                  'taoyuan_city': 0.01,
                                                  'yilan_county': 0.01,
                                                  'yunlin_county': 0.03},
                                      'age': { '': 0.23,
                                               'fifties': 0.01,
                                               'fourties': 0.11,
                                               'seventies': 0,
                                               'sixties': 0,
                                               'teens': 0.03,
                                               'thirties': 0.25,
                                               'twenties': 0.37},
                                      'gender': { '': 0.22,
                                                  'female': 0.27,
                                                  'male': 0.48,
                                                  'other': 0.03}},
                          'totalHrs': 73.85,
                          'users': 1331,
                          'validDurationSecs': 192572.99,
                          'validHrs': 53.49}},
  'multilingual': True,
  'name': 'Common Voice Corpus 5.1',
  'totalClips': 5540535,
  'totalDuration': 26015106972,
  'totalHrs': 7226,
  'totalValidDurationSecs': 20419110,
  'totalValidHrs': 5671,
  'version': '5.1.0'}